site_name: Todd Parsons

docs_dir: src
draft_docs: vault
site_dir: docs

theme:
  name: landing

  favicon: assets/tp.png
  avatar: assets/staff-picture.jpg
  tagline: |
    he/him /[tɒd pɑsənz](http://ipa-reader.xyz/?text=tɒd%20pɑsənz)/
  page_source: 
    link: https://github.com/TEParsons/toddparsons
  socials:
    - label: Email
      link: mailto:todd.e.parsons@gmail.com
      icon: at
    - label: GitHub
      link: https://github.com/TEParsons
      icon: [brands, github]
    - label: ORCiD
      link: https://orcid.org/0000-0002-6192-8414
      icon: [brands, orcid]
    - label: Google Scholar
      link: https://scholar.google.co.uk/citations?user=dPnWdLUAAAAJ&hl=en
      icon: [brands, google-scholar]
    - label: LinkedIn
      link: https://www.linkedin.com/in/todd-parsons-056a459a
      icon: [brands, linkedin]
  
  header_layout: 
    - tagline
    - ""
    - title
    - avatar
    - socials
  border_left: 2px solid var(--primary)
  avatar_size: 16rem
  round_avatar: True
  
  # colors
  primary_color: "#d9a35d"
  secondary_color: "#4862a6"
  tertiary_color: "#b75034"
  base_color: "#ffffff"
  mantle_color: "#f2f2f2"
  crust_color: "#d2d2d2"
  overlay_color: "#b2b2b2"
  text_color: "#161616"
  hltext_color: "#f2f2f2"
  # colors (dark)
  primary_color_dark: "#d9a35d"
  secondary_color_dark: "#46B1C9"
  tertiary_color_dark: "#D4ADCF"
  base_color_dark: "#212530"
  mantle_color_dark: "#111318"
  crust_color_dark: "#050608"
  overlay_color_dark: "#000000"
  text_color_dark: "#f2f2f2"
  hltext_color_dark: "#161616"

  # fonts
  body_font: Hind
  heading_font: Josefin Sans
  mono_font: JetBrains Mono


hooks:
  - hooks/md_filter.py
  - hooks/layout.py

markdown_extensions:
  - toc
  - attr_list
  - def_list
  - md_in_html
  - nl2br
