site_name: Todd Parsons

docs_dir: src
site_dir: docs

favicon: assets/tp.png
copyright: |
  Compiled from markdown using <a href="https://www.mkdocs.org/">MkDocs</a>, hosted via <a href="https://pages.github.com/">GitHub Pages</a>.

theme:
  name: mkdocs
  custom_dir: theme/
  avatar: assets/staff-picture.jpg
  tagline: |
    he/him /<a href="http://ipa-reader.xyz/?text=tɒd%20pɑsənz">tɒd pɑsənz</a>/
  page_source: 
    link: https://github.com/TEParsons/toddparsons
    icon: github
  socials:
    - label: Email
      link: mailto:todd.e.parsons@gmail.com
      icon: at
    - label: GitHub
      link: https://github.com/TEParsons
      icon: github
    - label: ORCiD
      link: https://orcid.org/0000-0002-6192-8414
      icon: orcid
    - label: Google Scholar
      link: https://scholar.google.co.uk/citations?user=dPnWdLUAAAAJ&hl=en
      icon: google-scholar
    - label: LinkedIn
      link: https://www.linkedin.com/in/todd-parsons-056a459a
      icon: linkedin

markdown_extensions:
  - toc
  - attr_list
  - def_list
  - md_in_html
  - nl2br
